import { Roboto_Slab, Roboto_Mono } from "next/font/google";

import ThemeContextProvider from "@/contexts/ThemeContextProvider";
import MarkdownContextProvider from "@/contexts/MarkdownContextProvider";

import "./globals.css";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-roboto-mono",
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-roboto_slab",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${robotoSlab.variable} min-h-screen overflow-hidden`}
      >
        <MarkdownContextProvider>
          <ThemeContextProvider>{children}</ThemeContextProvider>
        </MarkdownContextProvider>
      </body>
    </html>
  );
}
