import { roboto_slab, Roboto_Mono } from "next/font/google";
import ThemeContextProvider from "@/contexts/ThemeContextProvider";

import "./globals.css";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-roboto-mono",
});

const robotoSlab = roboto_slab({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-roboto_slab",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} ${robotoSlab.variable}`}>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
